server:
  port: 8888
spring:
  application:
    name: config-server
# this area was to be added to the spring cloud config deployed to git hub
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeonardoBatistaCarias/ms-course-spring2.5-configs
          #username: pass these values if repo is private
          #password:
          default-label: main
          search-paths:
          - 'greeting-service*'